name: CI 

on:
  push:  # Запускает workflow при каждом пуше
    branches:
      - main  # Укажите здесь свои ветки, если нужно

jobs:
  lint:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Install Ruff
        run: |
          pip install ruff  # Устанавливаем линтер Ruff

      - name: Run Ruff
        run: |
          ruff check --fix .  # Запускаем линтер для проверки всех файлов 
